(()=>{
const lang=(new URLSearchParams(location.search).get('lang')||'en').toLowerCase();
if(lang==='en')return;
const D={
es:{
'Structura Tools · SketchUp + Blender':'Structura Tools · SketchUp + Blender',
'Procedural tools':'Herramientas procedurales','for 3D production.':'para producción 3D.',
'Powerful plugins and add-ons for architecture and asset production — built around repeatable workflows, editable systems and production-ready output.':'Plugins y add-ons potentes para arquitectura y producción de assets, creados alrededor de workflows repetibles, sistemas editables y resultados listos para producción.',
'SketchUp plugins':'Plugins de SketchUp','Blender add-ons':'Add-ons de Blender',
'Parametric workflows':'Workflows paramétricos','Editable systems':'Sistemas editables','Production ready':'Listo para producción',
'Architecture production':'Producción arquitectónica','Model faster. Build smarter.':'Modela más rápido. Construye mejor.',
'Procedural tools for architectural modelling, parametric systems and production-ready geometry inside SketchUp.':'Herramientas procedurales para modelado arquitectónico, sistemas paramétricos y geometría lista para producción dentro de SketchUp.',
'Asset production':'Producción de assets','Generate. Customize. Produce.':'Genera. Personaliza. Produce.',
'Procedural asset generators for product design, interiors and environment production in Blender.':'Generadores procedurales de assets para diseño de producto, interiores y producción de entornos en Blender.',
'Explore SketchUp plugins':'Explorar plugins de SketchUp','Explore Blender roadmap':'Explorar roadmap de Blender',
'One ecosystem':'Un ecosistema','Different software.':'Software diferente.','Same production logic.':'La misma lógica de producción.',
'Procedural':'Procedural','Editable':'Editable','Production ready':'Listo para producción','Consistent':'Coherente',
'Start free · SketchUp':'Empieza gratis · SketchUp','Download free':'Descargar gratis','Current commercial release':'Lanzamiento comercial actual','Explore Windows':'Explorar Windows',
'Blender roadmap':'Roadmap Blender','From architecture tools':'De herramientas de arquitectura','to procedural asset systems.':'a sistemas procedurales de assets.',
'Build systems.':'Construye sistemas.','Not repetitive geometry.':'No geometría repetitiva.',
'Start with Floor & Wall':'Empezar con Floor & Wall','See Blender add-ons':'Ver add-ons de Blender',
'In development':'En desarrollo','Planned':'Planificado','Research':'Investigación','Preview':'Vista previa','Free':'Gratis','Early Access':'Early Access','Shared appliance family':'Familia compartida de electrodomésticos','Procedural refrigerators':'Neveras procedurales','Procedural ovens':'Hornos procedurales','Procedural dishwashers':'Lavavajillas procedurales','Related product: Kitchen remains a separate procedural kitchen system, with a dedicated integration layer for Appliance Gen.':'Producto relacionado: Kitchen sigue siendo un sistema procedural de cocinas independiente, con una capa de integración específica para Appliance Gen.','The Blender line is organized around Appliance Gen, a shared family built on common product DNA. Refrigerator Gen, Oven Gen and Dishwasher Gen are the first appliances in development. Kitchen remains a related but separate product, with its own Appliance Gen integration layer.':'La línea de Blender se organiza alrededor de Appliance Gen, una familia compartida basada en un DNA de producto común. Refrigerator Gen, Oven Gen y Dishwasher Gen son los primeros electrodomésticos en desarrollo. Kitchen sigue siendo un producto relacionado pero independiente, con su propia capa de integración para Appliance Gen.','· In development':'· En desarrollo'
},
ca:{
'Procedural tools':'Eines procedurals','for 3D production.':'per a producció 3D.','SketchUp plugins':'Plugins de SketchUp','Blender add-ons':'Add-ons de Blender',
'Parametric workflows':'Fluxos paramètrics','Editable systems':'Sistemes editables','Production ready':'Preparat per a producció','Architecture production':'Producció arquitectònica','Asset production':'Producció d’assets',
'Model faster. Build smarter.':'Modela més ràpid. Construeix millor.','Generate. Customize. Produce.':'Genera. Personalitza. Produeix.',
'Explore SketchUp plugins':'Explora plugins de SketchUp','Explore Blender roadmap':'Explora el roadmap de Blender','One ecosystem':'Un ecosistema','Different software.':'Programari diferent.','Same production logic.':'La mateixa lògica de producció.',
'Procedural':'Procedural','Editable':'Editable','Production ready':'Preparat per a producció','Consistent':'Coherent','Start free · SketchUp':'Comença gratis · SketchUp','Download free':'Descarrega gratis','Current commercial release':'Llançament comercial actual','Explore Windows':'Explora Windows','Blender roadmap':'Roadmap Blender','Build systems.':'Construeix sistemes.','Not repetitive geometry.':'No geometria repetitiva.','Start with Floor & Wall':'Comença amb Floor & Wall','See Blender add-ons':'Veure add-ons de Blender','In development':'En desenvolupament','Planned':'Planificat','Research':'Recerca','Preview':'Vista prèvia','Free':'Gratis','Early Access':'Accés anticipat','Shared appliance family':'Família compartida d’electrodomèstics','Procedural refrigerators':'Neveres procedurals','Procedural ovens':'Forns procedurals','Procedural dishwashers':'Rentavaixelles procedurals','Related product: Kitchen remains a separate procedural kitchen system, with a dedicated integration layer for Appliance Gen.':'Producte relacionat: Kitchen continua sent un sistema procedural de cuina independent, amb una capa d’integració específica per a Appliance Gen.','The Blender line is organized around Appliance Gen, a shared family built on common product DNA. Refrigerator Gen, Oven Gen and Dishwasher Gen are the first appliances in development. Kitchen remains a related but separate product, with its own Appliance Gen integration layer.':'La línia de Blender s’organitza al voltant d’Appliance Gen, una família compartida basada en un DNA de producte comú. Refrigerator Gen, Oven Gen i Dishwasher Gen són els primers electrodomèstics en desenvolupament. Kitchen continua sent un producte relacionat però independent, amb la seva pròpia capa d’integració per a Appliance Gen.','· In development':'· En desenvolupament'
},
it:{
'Procedural tools':'Strumenti procedurali','for 3D production.':'per la produzione 3D.','SketchUp plugins':'Plugin SketchUp','Blender add-ons':'Add-on Blender','Parametric workflows':'Workflow parametrici','Editable systems':'Sistemi modificabili','Production ready':'Pronto per la produzione','Architecture production':'Produzione architettonica','Asset production':'Produzione di asset','Model faster. Build smarter.':'Modella più velocemente. Costruisci meglio.','Generate. Customize. Produce.':'Genera. Personalizza. Produci.','Explore SketchUp plugins':'Esplora i plugin SketchUp','Explore Blender roadmap':'Esplora la roadmap Blender','One ecosystem':'Un ecosistema','Different software.':'Software diversi.','Same production logic.':'La stessa logica di produzione.','Procedural':'Procedurale','Editable':'Modificabile','Production ready':'Pronto per la produzione','Consistent':'Coerente','Start free · SketchUp':'Inizia gratis · SketchUp','Download free':'Scarica gratis','Current commercial release':'Release commerciale attuale','Explore Windows':'Esplora Windows','Blender roadmap':'Roadmap Blender','Build systems.':'Costruisci sistemi.','Not repetitive geometry.':'Non geometria ripetitiva.','Start with Floor & Wall':'Inizia con Floor & Wall','See Blender add-ons':'Vedi gli add-on Blender','In development':'In sviluppo','Planned':'Pianificato','Research':'Ricerca','Preview':'Anteprima','Free':'Gratis','Early Access':'Accesso anticipato','Shared appliance family':'Famiglia condivisa di elettrodomestici','Procedural refrigerators':'Frigoriferi procedurali','Procedural ovens':'Forni procedurali','Procedural dishwashers':'Lavastoviglie procedurali','Related product: Kitchen remains a separate procedural kitchen system, with a dedicated integration layer for Appliance Gen.':'Prodotto correlato: Kitchen resta un sistema procedurale per cucine separato, con un livello di integrazione dedicato per Appliance Gen.','The Blender line is organized around Appliance Gen, a shared family built on common product DNA. Refrigerator Gen, Oven Gen and Dishwasher Gen are the first appliances in development. Kitchen remains a related but separate product, with its own Appliance Gen integration layer.':'La linea Blender è organizzata attorno ad Appliance Gen, una famiglia condivisa basata su un DNA di prodotto comune. Refrigerator Gen, Oven Gen e Dishwasher Gen sono i primi elettrodomestici in sviluppo. Kitchen resta un prodotto correlato ma separato, con un proprio livello di integrazione per Appliance Gen.','· In development':'· In sviluppo'
},
fr:{
'Procedural tools':'Outils procéduraux','for 3D production.':'pour la production 3D.','SketchUp plugins':'Plugins SketchUp','Blender add-ons':'Add-ons Blender','Parametric workflows':'Workflows paramétriques','Editable systems':'Systèmes modifiables','Production ready':'Prêt pour la production','Architecture production':'Production architecturale','Asset production':'Production d’assets','Model faster. Build smarter.':'Modélisez plus vite. Construisez mieux.','Generate. Customize. Produce.':'Générez. Personnalisez. Produisez.','Explore SketchUp plugins':'Explorer les plugins SketchUp','Explore Blender roadmap':'Explorer la roadmap Blender','One ecosystem':'Un écosystème','Different software.':'Logiciels différents.','Same production logic.':'La même logique de production.','Procedural':'Procédural','Editable':'Modifiable','Production ready':'Prêt pour la production','Consistent':'Cohérent','Start free · SketchUp':'Commencer gratuitement · SketchUp','Download free':'Télécharger gratuitement','Current commercial release':'Version commerciale actuelle','Explore Windows':'Découvrir Windows','Blender roadmap':'Roadmap Blender','Build systems.':'Construisez des systèmes.','Not repetitive geometry.':'Pas de géométrie répétitive.','Start with Floor & Wall':'Commencer avec Floor & Wall','See Blender add-ons':'Voir les add-ons Blender','In development':'En développement','Planned':'Planifié','Research':'Recherche','Preview':'Aperçu','Free':'Gratuit','Early Access':'Accès anticipé','Shared appliance family':'Famille partagée d’appareils électroménagers','Procedural refrigerators':'Réfrigérateurs procéduraux','Procedural ovens':'Fours procéduraux','Procedural dishwashers':'Lave-vaisselle procéduraux','Related product: Kitchen remains a separate procedural kitchen system, with a dedicated integration layer for Appliance Gen.':'Produit associé : Kitchen reste un système procédural de cuisine distinct, avec une couche d’intégration dédiée à Appliance Gen.','The Blender line is organized around Appliance Gen, a shared family built on common product DNA. Refrigerator Gen, Oven Gen and Dishwasher Gen are the first appliances in development. Kitchen remains a related but separate product, with its own Appliance Gen integration layer.':'La gamme Blender est organisée autour d’Appliance Gen, une famille partagée fondée sur un ADN produit commun. Refrigerator Gen, Oven Gen et Dishwasher Gen sont les premiers appareils en développement. Kitchen reste un produit associé mais distinct, avec sa propre couche d’intégration pour Appliance Gen.','· In development':'· En développement'
},
de:{
'Procedural tools':'Prozedurale Werkzeuge','for 3D production.':'für die 3D-Produktion.','SketchUp plugins':'SketchUp Plugins','Blender add-ons':'Blender Add-ons','Parametric workflows':'Parametrische Workflows','Editable systems':'Editierbare Systeme','Production ready':'Produktionsbereit','Architecture production':'Architekturproduktion','Asset production':'Asset-Produktion','Model faster. Build smarter.':'Schneller modellieren. Intelligenter bauen.','Generate. Customize. Produce.':'Generieren. Anpassen. Produzieren.','Explore SketchUp plugins':'SketchUp Plugins entdecken','Explore Blender roadmap':'Blender Roadmap entdecken','One ecosystem':'Ein Ökosystem','Different software.':'Unterschiedliche Software.','Same production logic.':'Dieselbe Produktionslogik.','Procedural':'Prozedural','Editable':'Editierbar','Production ready':'Produktionsbereit','Consistent':'Konsistent','Start free · SketchUp':'Kostenlos starten · SketchUp','Download free':'Kostenlos herunterladen','Current commercial release':'Aktuelle kommerzielle Version','Explore Windows':'Windows entdecken','Blender roadmap':'Blender Roadmap','Build systems.':'Systeme bauen.','Not repetitive geometry.':'Keine repetitive Geometrie.','Start with Floor & Wall':'Mit Floor & Wall starten','See Blender add-ons':'Blender Add-ons ansehen','In development':'In Entwicklung','Planned':'Geplant','Research':'Forschung','Preview':'Vorschau','Free':'Kostenlos','Early Access':'Early Access','Shared appliance family':'Gemeinsame Gerätefamilie','Procedural refrigerators':'Prozedurale Kühlschränke','Procedural ovens':'Prozedurale Backöfen','Procedural dishwashers':'Prozedurale Geschirrspüler','Related product: Kitchen remains a separate procedural kitchen system, with a dedicated integration layer for Appliance Gen.':'Verwandtes Produkt: Kitchen bleibt ein separates prozedurales Küchensystem mit einer eigenen Integrationsschicht für Appliance Gen.','The Blender line is organized around Appliance Gen, a shared family built on common product DNA. Refrigerator Gen, Oven Gen and Dishwasher Gen are the first appliances in development. Kitchen remains a related but separate product, with its own Appliance Gen integration layer.':'Die Blender-Linie ist um Appliance Gen organisiert, eine gemeinsame Familie auf Basis einer einheitlichen Produkt-DNA. Refrigerator Gen, Oven Gen und Dishwasher Gen sind die ersten Geräte in Entwicklung. Kitchen bleibt ein verwandtes, aber separates Produkt mit einer eigenen Integrationsschicht für Appliance Gen.','· In development':'· In Entwicklung'
},
pt:{
'Procedural tools':'Ferramentas procedurais','for 3D production.':'para produção 3D.','SketchUp plugins':'Plugins SketchUp','Blender add-ons':'Add-ons Blender','Parametric workflows':'Workflows paramétricos','Editable systems':'Sistemas editáveis','Production ready':'Pronto para produção','Architecture production':'Produção arquitetónica','Asset production':'Produção de assets','Model faster. Build smarter.':'Modele mais rápido. Construa melhor.','Generate. Customize. Produce.':'Gere. Personalize. Produza.','Explore SketchUp plugins':'Explorar plugins SketchUp','Explore Blender roadmap':'Explorar roadmap Blender','One ecosystem':'Um ecossistema','Different software.':'Software diferente.','Same production logic.':'A mesma lógica de produção.','Procedural':'Procedural','Editable':'Editável','Production ready':'Pronto para produção','Consistent':'Consistente','Start free · SketchUp':'Começar grátis · SketchUp','Download free':'Descarregar grátis','Current commercial release':'Lançamento comercial atual','Explore Windows':'Explorar Windows','Blender roadmap':'Roadmap Blender','Build systems.':'Construa sistemas.','Not repetitive geometry.':'Não geometria repetitiva.','Start with Floor & Wall':'Começar com Floor & Wall','See Blender add-ons':'Ver add-ons Blender','In development':'Em desenvolvimento','Planned':'Planeado','Research':'Investigação','Preview':'Pré-visualização','Free':'Grátis','Early Access':'Acesso antecipado','Shared appliance family':'Família partilhada de eletrodomésticos','Procedural refrigerators':'Frigoríficos procedurais','Procedural ovens':'Fornos procedurais','Procedural dishwashers':'Máquinas de lavar loiça procedurais','Related product: Kitchen remains a separate procedural kitchen system, with a dedicated integration layer for Appliance Gen.':'Produto relacionado: Kitchen continua a ser um sistema procedural de cozinha separado, com uma camada de integração dedicada para Appliance Gen.','The Blender line is organized around Appliance Gen, a shared family built on common product DNA. Refrigerator Gen, Oven Gen and Dishwasher Gen are the first appliances in development. Kitchen remains a related but separate product, with its own Appliance Gen integration layer.':'A linha Blender está organizada em torno do Appliance Gen, uma família partilhada baseada num DNA de produto comum. Refrigerator Gen, Oven Gen e Dishwasher Gen são os primeiros eletrodomésticos em desenvolvimento. Kitchen continua a ser um produto relacionado, mas separado, com a sua própria camada de integração para Appliance Gen.','· In development':'· Em desenvolvimento'
}
};
const dict=D[lang]||{};
function translate(){
  document.documentElement.lang=lang;
  const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  const nodes=[];while(w.nextNode())nodes.push(w.currentNode);
  nodes.forEach(n=>{const raw=n.nodeValue,t=raw.trim();if(t&&dict[t])n.nodeValue=raw.replace(t,dict[t]);});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(translate,20),{once:true});else setTimeout(translate,20);
})();
